# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [4]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

height1 = np.array(height)
weight1 = np.array(weight)

bmi = weight1 / (height1 ** 2) * 730

print(bmi)

[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [32]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass

# np.array to stack them
# .reshape() to change the shape 
    #(rows,columns)
    
# np.arange() to choose a range

def makeMatrix(start, end, rows, columns):
    return np.arange(start,end).reshape(rows, columns)

print(makeMatrix(2,14,3,4))
    
def makeMatrix2(low, high, shape):
    return np.random.uniform(low, high, shape)
print(makeMatrix2(5,100,(3,5)))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[61.85047331  9.33424625 40.58131632 62.16851394 25.97348839]
 [47.00850228 28.32056467 69.13844784 37.669504   86.18506552]
 [49.332479   24.39456949 51.45471338 98.46558217 59.97985043]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [36]:
import csv
import numpy as np
import statistics as s

#Test to make sure you have the correct data
def open_csv(filename, d = ','): # d is how our data will be separated
    # Define an empty list to store data
    data = []
    
    with open(filename, encoding='utf-8') as mData:
        # Use the CSV reader method to create a python list
        info = csv.reader(mData, delimiter = d)
        
        #loop over info and append to data list
        for row in info:
            data.append(row)
    return data
csv_data = open_csv('files/files/redsox_2018_hitting.txt')
# print(csv_data)

In [42]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

data_2018 = load_data('files/files/redsox_2018_hitting.txt')
data_2017 = load_data('files/files/redsox_2017_hitting.txt')

slg_2018 = s.mean(data_2018['SLG'])
slg_2017 = s.mean(data_2017['SLG'])
print(f" The average SLG in 2018 was: {slg_2018}")
print(f"\n The average SLG in 2017 was: {slg_2017}")

 The average SLG in 2018 was: 0.38750001788139343

 The average SLG in 2017 was: 0.393347829580307
